# Module: NumPy Assignments
## Lesson: NumPy

### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.

In [99]:
import numpy as np

arr = np.random.randint(1, 21, size=(5,5))
print("Original array:")
print(arr)

arr[:,2] = 1
print("After replacing 3rd col with 1:")
print(arr)

Original array:
[[19 14  9 13  6]
 [16  5 19  3 20]
 [ 9 18  8  7 20]
 [12  8 10  3 16]
 [ 1  9 16  5  6]]
After replacing 3rd col with 1:
[[19 14  1 13  6]
 [16  5  1  3 20]
 [ 9 18  1  7 20]
 [12  8  1  3 16]
 [ 1  9  1  5  6]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [100]:
import numpy as np

arr = np.random.randint(1, 17, size=(4,4))
print("Original array:")
print(arr)

np.fill_diagonal(arr, 0)
print("After filling 0 diagonally:")
print(arr)

Original array:
[[10  3 16 11]
 [ 3 12 12  6]
 [ 8  5  8  3]
 [11  4  8 11]]
After filling 0 diagonally:
[[ 0  3 16 11]
 [ 3  0 12  6]
 [ 8  5  0  3]
 [11  4  8  0]]


### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.

In [101]:
import numpy as np

arr = np.random.randint(1, 37, size=(6,6))
print("Original array:")
print(arr)

print("Extract 3rd to 5th rows and 2nd to 4th columns:")
print(arr[2:5, 1:4])

Original array:
[[ 5  7 24 10 24 22]
 [18 15 13 31  5 28]
 [22 29 25  6 29 11]
 [32 17 33 17 35 16]
 [25 13 36 11 16 32]
 [27  8  9  3 19 18]]
Extract 3rd to 5th rows and 2nd to 4th columns:
[[29 25  6]
 [17 33 17]
 [13 36 11]]


2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [102]:
import numpy as np

arr = np.random.randint(1, 100, size=(5,5))
print("Original array:")
print(arr)

print("Extract elements on border:")
top = arr[0, :]
bottom = arr[-1, :]
left = arr[1:-1, 0]
right = arr[1:-1, -1]
border = np.concatenate([top, left, bottom, right])
print(border)

Original array:
[[91 31 79 36 17]
 [91 10 39 79 22]
 [29 25 38  9 47]
 [92  2 31  7 33]
 [91 36 62 20 20]]
Extract elements on border:
[91 31 79 36 17 91 29 92 91 36 62 20 20 22 47 33]


### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.

In [17]:
import numpy as np

arr1 = np.random.randint(1, 100, size=(3,4))
arr2 = np.random.randint(1, 100, size=(3,4))

print("Array 1:")
print(arr1)

print("Array 2:")
print(arr2)

# Addition
print("Array addition:")
print(arr1 + arr2)

# Subtraction
print("Array subtraction:")
print(arr1 - arr2)

# Multiplication
print("Array multiplication:")
print(arr1 * arr2)

# Division
print("Array division:")
print(np.round(arr1 / arr2, 1))

Array 1:
[[85 84 69 16]
 [37 45 69 81]
 [34 10 25 29]]
Array 2:
[[81 40 87 44]
 [16 87 26 98]
 [32 68  1 61]]
Array addition:
[[166 124 156  60]
 [ 53 132  95 179]
 [ 66  78  26  90]]
Array subtraction:
[[  4  44 -18 -28]
 [ 21 -42  43 -17]
 [  2 -58  24 -32]]
Array multiplication:
[[6885 3360 6003  704]
 [ 592 3915 1794 7938]
 [1088  680   25 1769]]
Array division:
[[ 1.   2.1  0.8  0.4]
 [ 2.3  0.5  2.7  0.8]
 [ 1.1  0.1 25.   0.5]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [ ]:
import numpy as np

arr = np.random.randint(1, 17, size=(4,4))
print("Original array:")
print(arr)

# Row-wise sum
print("Row-wise sum:")
print(np.sum(arr, axis=0))

# Column-wise sum
print("Column-wise sum:")
print(np.sum(arr, axis=1))

Original array:
[[10 11  3  3]
 [ 1  1 13  2]
 [11  4  2  4]
 [ 4  1  3  6]]
Row-wise sum:
[26 17 21 15]
Column-wise sum:
[27 17 21 14]


### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.

In [ ]:
import numpy as np

arr = np.random.randint(1, 100, size=(5,5))
print("Original array:")
print(arr)


print(f"Mean value: {np.mean(arr)}")
print(f"Median value: {np.median(arr)}")
print(f"Standard deviation value: {np.std(arr)}")
print(f"Variance value: {np.var(arr)}")

Original array:
[[ 7 65 57  1 53]
 [ 1 84 47 53 64]
 [46 42 15 45 86]
 [ 8 74 22 18 86]
 [20 96 17 78 52]]
Mean value: 45.48
Median value: 47.0
Standard deviation value: 28.814052127390898
Variance value: 830.2495999999999


2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [ ]:
import numpy as np

arr = np.random.randint(1, 10, size=(3,3))
print("Original array:")
print(arr)

mean = np.mean(arr)
stddev = np.std(arr)
normalized = (arr - mean) / stddev
print(f"After normalize: {normalized}")

Original array:
[[5 7 1]
 [2 6 6]
 [6 1 7]]
After normalize: [[ 0.18814417  1.03479296 -1.50515339]
 [-1.081829    0.61146856  0.61146856]
 [ 0.61146856 -1.50515339  1.03479296]]


### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.

In [31]:
import numpy as np

arr2d = np.random.randint(1, 10, size=(3,3))
print("2D array:")
print(arr2d)

arr1d = np.random.randint(1, 10, size=(3,))
print('1D array:')
print(arr1d)

print("Add 1D array to 2D array using braodcasting method:")
print(arr2d + arr1d)

2D array:
[[8 4 5]
 [1 9 6]
 [1 8 9]]
1D array:
[7 1 5]
Add 1D array to 2D array using braodcasting method:
[[15  5 10]
 [ 8 10 11]
 [ 8  9 14]]


2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [33]:
import numpy as np

arr2d = np.random.randint(1, 10, size=(4,4))
print("2D array:")
print(arr2d)

arr1d = np.random.randint(1, 10, size=(4,))
print('1D array:')
print(arr1d)

print("Subtract 1D array from 2D array using braodcasting method:")
print(arr2d - arr1d)

2D array:
[[1 7 5 3]
 [1 3 4 2]
 [3 5 9 1]
 [3 8 9 8]]
1D array:
[2 7 3 2]
Subtract 1D array from 2D array using braodcasting method:
[[-1  0  2  1]
 [-1 -4  1  0]
 [ 1 -2  6 -1]
 [ 1  1  6  6]]


### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.

In [105]:
import numpy as np

arr = np.random.randint(1, 10, size=(3,3))
print("Original array:")
print(arr)

# Calculation determinant
print("Determinant:")
print(np.linalg.det(arr))

# Calucation inverse
print("Inverse:")
print(np.linalg.inv(arr))

# Calculation eigenvalues
print("Eigenvalues:")
print(np.linalg.eigvals(arr))

Original array:
[[4 6 9]
 [1 8 4]
 [9 1 8]]
Determinant:
-230.99999999999994
Inverse:
[[-0.25974026  0.16883117  0.20779221]
 [-0.12121212  0.21212121  0.03030303]
 [ 0.30735931 -0.21645022 -0.11255411]]
Eigenvalues:
[17.03111587 -2.48632333  5.45520746]


2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

In [107]:
import numpy as np

arr1 = np.random.randint(1, 10, size=(2,3))
print("Array 1:")
print(arr1)

arr2 = np.random.randint(1, 10, size=(3,2))
print("Array 2:")
print(arr2)

# Multiplication of matrices
print("Matrix multiplication:")
print("Using 'np.matmul()':")
print(np.matmul(arr1, arr2))
print("Using '@':")
print((arr1 @ arr2))
print("Using 'dot'")
print(np.dot(arr1, arr2))

Array 1:
[[6 4 7]
 [8 4 7]]
Array 2:
[[9 6]
 [8 1]
 [3 9]]
Matrix multiplication:
Using 'np.matmul()':
[[107 103]
 [125 115]]
Using '@':
[[107 103]
 [125 115]]
Using 'dot'
[[107 103]
 [125 115]]


### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).

In [108]:
import numpy as np

arr = np.random.randint(1, 10, size=(3,3))
print("Original array:")
print(arr)

print("After reshaping (1, 9):")
print(arr.reshape(1,9))

print("After reshaping (9, 1):")
print(arr.reshape(9,1))

Original array:
[[3 1 2]
 [4 9 2]
 [1 2 5]]
After reshaping (1, 9):
[[3 1 2 4 9 2 1 2 5]]
After reshaping (9, 1):
[[3]
 [1]
 [2]
 [4]
 [9]
 [2]
 [1]
 [2]
 [5]]


2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

In [48]:
import numpy as np

arr = np.random.randint(1, 9, size=(5,5))
print("Original array:")
print(arr)

print("After flatten:")
flat = arr.flatten()
print(flat)

print("After reshape:")
reshape = arr.reshape(5,5)
print(reshape)

Original array:
[[8 7 8 5 5]
 [8 3 7 1 2]
 [4 1 5 1 6]
 [2 8 3 5 4]
 [3 3 4 3 6]]
After flatten:
[8 7 8 5 5 8 3 7 1 2 4 1 5 1 6 2 8 3 5 4 3 3 4 3 6]
After reshape:
[[8 7 8 5 5]
 [8 3 7 1 2]
 [4 1 5 1 6]
 [2 8 3 5 4]
 [3 3 4 3 6]]


### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.

In [112]:
import numpy as np

arr = np.random.randint(1, 9, size=(5,5))
print("Original array:")
print(arr)

print(f"Element at left top corner: {arr[0,0]}")
print(f"Element at right top corner: {arr[0,-1]}")
print(f"Element at left bottom corner: {arr[-1,0]}")
print(f"Element at right bottom corner: {arr[-1,-1]}")
print(f"All elements at corners: {arr[[0, 0, -1, -1], [0, -1, 0, -1]]}")

Original array:
[[2 8 1 5 1]
 [1 5 2 4 6]
 [7 8 7 7 2]
 [6 5 4 8 7]
 [2 3 1 8 5]]
Element at left top corner: 2
Element at right top corner: 1
Element at left bottom corner: 2
Element at right bottom corner: 5
All elements at corners: [2 1 2 5]


2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

In [113]:
import numpy as np

arr = np.random.randint(1, 15, size=(4,4))
print("Original array:")
print(arr)

print("All elements greater than 10:")
arr[arr > 10] = 10
print(arr)

Original array:
[[ 2 12  5 13]
 [ 5  7  9  2]
 [ 2 13 11  7]
 [ 6  3  8 11]]
All elements greater than 10:
[[ 2 10  5 10]
 [ 5  7  9  2]
 [ 2 10 10  7]
 [ 6  3  8 10]]


### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.

In [115]:
dtypes = [('name', 'U20'),    # ''U20' = unicode string (up to 20 characters)
          ('age', 'i4'),      # 'i4' = 32-bit integer
          ('weight', 'f4')]   # 'f4' = 32-bit float

arr = np.array([('Htet',24,61),
                 ('Aung',31,55),
                 ('Lynn',26,65)], dtype=dtypes)

print("Original array:")
print(arr)

print("Sort array:")
sorted = np.sort(arr, order='age')
print(sorted)

print("Check field names:")
print(arr.dtype.names)

Original array:
[('Htet', 24, 61.) ('Aung', 31, 55.) ('Lynn', 26, 65.)]
Sort array:
[('Htet', 24, 61.) ('Lynn', 26, 65.) ('Aung', 31, 55.)]
Check field names:
('name', 'age', 'weight')


2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

In [ ]:
dtypes = np.dtype([('x', 'i4'),    # ''U20' = unicode string (up to 20 characters)
                   ('y', 'i4')])    # 'i4' = 32-bit integer

# 1D array
arr = np.array([(12,23),
                (22,71),
                (18,43),
                (30,78)], dtype=dtypes)

print("Check field names:")
print(arr.dtype.names)

print("Original array:")
print(arr)

# Euclidean distance calculation
# print(arr['x'][:, np.newaxis])
# print(arr['x'])
# print(arr['x'][:, np.newaxis] - arr['x'])
eu_dst = np.sqrt((arr['x'][:,np.newaxis] - arr['x'])**2 + (arr['y'][:, np.newaxis]- arr['y'])**2)
print("After distance calculation:")
print(eu_dst)

Check field names:
('x', 'y')
Original array:
[(12, 23) (22, 71) (18, 43) (30, 78)]
After distance calculation:
[[ 0.         49.03060269 20.88061302 57.87054518]
 [49.03060269  0.         28.28427125 10.63014581]
 [20.88061302 28.28427125  0.         37.        ]
 [57.87054518 10.63014581 37.          0.        ]]


### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.

In [ ]:
import numpy

arr = np.random.randint(1, 15, size=(4,4))
print("Original array:")
print(arr)

print("Masked array greater than 10:")
msk_g10 = np.ma.masked_greater(arr, 10)
print(msk_g10)

print("Sum of the unmasked elements:")
print(msk_g10.sum())

Original array:
[[ 4  8 14 10]
 [13  8 10  3]
 [ 2 11  4 14]
 [11 13 11  5]]
Masked array greater than 10:
[[4 8 -- 10]
 [-- 8 10 3]
 [2 -- 4 --]
 [-- -- -- 5]]
Sum of the unmasked elements:
54


2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [135]:
import numpy as np

np.eye(3, dtype=bool)

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [140]:
import numpy as np

arr = np.random.randint(1, 15, size=(3,3))
print("Original array:")
print(arr)

print("Masked diagonal elements:")
msk_arr = np.ma.masked_array(arr, mask = np.eye(3, dtype=bool))
print(msk_arr)

print("Replaced mean value of unmasked elements:")
print(msk_arr.filled(msk_arr.mean()))

Original array:
[[12 14  8]
 [ 3 14  8]
 [ 1  3  6]]
Masked diagonal elements:
[[-- 14 8]
 [3 -- 8]
 [1 3 --]]
Replaced mean value of unmasked elements:
[[ 6 14  8]
 [ 3  6  8]
 [ 1  3  6]]
